FROM openjdk:11.0.5-slim

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/slallem/tuto-springboot-dockerfile/raw/master/examples/demo.jar -O my-app.jar

RUN groupadd -r my-app-group && useradd -r -g my-app-group my-app-user
USER my-app-user

EXPOSE 8080

ENTRYPOINT exec java -XshowSettings:vm $JAVA_OPTS -jar /my-app.jar

# To build and run this example:

# $ docker build -t my-app .
# then
# $ docker run -P my-app
# or bind specific port (-p real-host-port:image-exposed-port)
# $ docker run -p 80:8080 my-app

# To run in background (-d = "detached" container)
# $ docker run -d -p 80:8080 my-app
